title: GhostNet
author: Ghost
email: ghost.chat.net@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GhostNet Blog for Release

twitter_username: 
github_username:  

sass:
    style: dark